---
- name: Node.js
  hosts: app2
#  hosts: app1
  become: true

  tasks:
    - name: update all installed packages
      yum:
        update_only: true
        update_cache: true
      become: true

    - name: Download node.js packages
      ansible.builtin.get_url:
        url: http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz
        dest: /home/centos
      become: true

    - name: Extract foo.tgz into /var/lib/foo
      ansible.builtin.unarchive:
        src: /home/centos/node-v0.10.30-linux-x64.tar.gz
        dest: /usr/local
        remote_src: yes
        extra_opts: --strip-components=1

    - name: install npm
      yum:
        name: npm
        state: present
      become: true


