---
- name: Node.js
  hosts: app2
#  hosts: app1
  become: true

  tasks:
    - name: update all installed packages
      yum:
        update_only: true
        update_cache: true
      become: true

    - name: Check if /usr/local/bin/node exists
      stat:
        path: /usr/local/bin/node
      register: node_bin

    - name: Remove existing Node.js installation in /usr/local if found
      file:
        path: /usr/local
        state: absent
        recurse: yes
      when: node_bin.stat.exists

    - name: Remove files and directories from previous tar extraction
      file:
        path: /usr/local/node-v18.20.8.tar.gz  # Replace with the 'dest' directory from your unarchive task
        state: directory
        recurse: yes

#    - name: Download node.js packages
#      ansible.builtin.get_url:
##        url: http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz
#        url: https://nodejs.org/dist/v18.20.8/node-v18.20.8.tar.gz
#        dest: /home/centos
#      become: true
#
#    - name: Extract foo.tgz into /var/lib/foo
#      ansible.builtin.unarchive:
#        src: /home/centos/node-v18.20.8.tar.gz
#        dest: /usr/local
#        remote_src: yes
#        extra_opts: --strip-components=1


