---
- name: Node.js
  hosts: app2
#  hosts: app1
  become: true
  vars:
    vault_url_prefix: "http://vault.centos.org"
    repositories:
      - name: base
        path: os
      - name: updates
        path: updates
      - name: extras
        path: extras
      - name: centosplus
        path: centosplus

  tasks:
    - name: update all installed packages
      yum:
        update_only: true
        update_cache: true
      become: true

    - name: Download node.js packages
      ansible.builtin.get_url:
        url: https://rpm.nodesource.com/setup_10.x
        dest: /home/centos
      become: true

    - name: Comment out mirrorlist lines in CentOS-Base.repo
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^mirrorlist='
        state: absent
#        owner: root
        line: '#mirrorlist='
        insertbefore: '^#baseurl='

    - name: Set baseurl for each repository to CentOS Vault
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^#?baseurl=http://mirror.centos.org/centos/$releasever/{{ item.path }}/$basearch/'
        line: 'baseurl={{ vault_url_prefix}}/centos/$releasever/{{ item.path }}/$basearch/'
      loop: "{{ repositories }}"

#    - name: install node.js
#      yum:
#        name: nodejs
#        state: present
#      become: true
#
#    - name: install npm
#      yum:
#        name: npm
#        state: present
#      become: true


