---
- name: Node.js
  hosts: app2
#  hosts: app1
  become: true

  tasks:
    - name: install node.js
      yum:
        name: nodejs20
        state: present

    - name: install npm
      service:
        name: npm
        state: present


