---
- name: Make changes to the Centos base file in remote server
  hosts: app2
  become: true
  vars:
    vault_url_prefix: "http://vault.centos.org"
    repositories:
      - name: base
        path: os
      - name: updates
        path: updates
      - name: extras
        path: extras
      - name: centosplus
        path: centosplus

  tasks:
    - name: Comment out mirrorlist lines in CentOS-Base.repo
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^mirrorlist='
        state: absent
        line: '#mirrorlist='
        insertbefore: '^#baseurl='

#   Still working on it
    - name: Set baseurl for each repository to CentOS Vault
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^#?baseurl=http://mirror.centos.org/centos/$releasever/{{ item.path }}/$basearch/'
        line: 'baseurl={{ vault_url_prefix}}/centos/$releasever/{{ item.path }}/$basearch/'
      loop: "{{ repositories }}"