---
- name: uninstall previous nodejs version
  hosts: app2
  become: true

  tasks:
    - name: Check if /usr/local/bin/node exists
      stat:
        path: /usr/local/bin/node
      register: node_bin

    - name: Remove existing Node.js installation in /usr/local if found
      file:
        path: /usr/local
        state: absent
        recurse: yes
      when: node_bin.stat.exists

#    - name: Extract Node.js tar.gz into /usr/local
#      ansible.builtin.unarchive:
#        src: /home/centos/node-v18.20.8.tar.gz
#        dest: /usr/local
#        remote_src: yes
#        extra_opts: --strip-components=1