---
- name: Create Jenkins user on agent
  hosts: b1
  become: yes
#  vars:
#    root_pass: Jenkins

  tasks:
    - name: install java
      yum:
        name: java-17
        state: present

    - name: Create user jenkins
      ansible.builtin.user:
        name: jenkins
        create_home: yes
        shell: /bin/bash
#        update_password: on_create
        # when inputing a password on ansible playbook, it has to be written in this format
#        password: "{{root_pass | password_hash('sha512')}}"

    - name: Create .ssh folder
      file:
        path: /var/lib/jenkins/.ssh
        state: directory
        owner: jenkins
        mode: 0700

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/.ssh/
        dest: /var/lib/jenkins/.ssh
        owner: jenkins
#        remote_src: true
        mode: 0700
#    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
#      community.crypto.openssh_keypair:
#        path: /var/lib/jenkins/.ssh/id_ssh_rsa
##       force used only when the key already exists
#        force: true
#        owner: jenkins
#        mode: 0700

...