---
- name: Create Jenkins user on agent
  hosts: a1
  become: yes

  tasks:
    - name: install java
      yum:
        name: openjdk-17-jre-headless
        state: present

    - name: Create user jenkins
      ansible.builtin.user:
        name: jenkins
        create_home: yes
        shell: /bin/bash
        update_password: on_create
        password: Jenkins

...