---
- name: Create Jenkins user on agent
  hosts: a1
  become: yes
  vars:
    root_pass: Jenkins

  tasks:
    - name: install java
      yum:
        name: java-17
        state: present

    - name: Create user jenkins
      ansible.builtin.user:
        name: jenkins
        create_home: yes
        shell: /bin/bash
        update_password: on_create
        # when inputing a password on ansible playbook, it has to be written in this format
        password: "{{root_pass | password_hash('sha512')}}"

...